group: "southwark-freecycle"
per_page: 100
keywords:
  - aquarium
  - camp
  - cherry
  - emulsion
  - ergodox
  - fan
  - fish
  - kitchen
  - ladder
  - lamp
  - mac
  - marine
  - new
  - paint
  - playstation
  - programming
  - roller
  - suitcase
  - unused
  - xbox
  - tent
  - tarp
