groups:
  - southwark-freecycle
  - towerhamletsfreecycle
  - LewishamUK
  - LambethUK
  - HackneyUK
per_page: 100
keywords:
  - aquarium
  - camp
  - cherry
  - emulsion
  - ergodox
  - fan
  - fish
  - ladder
  - lamp
  - mac
  - marine
  - new
  - paint
  - playstation
  - programming
  - roller
  - suitcase
  - unused
  - xbox
  - weights
  - dumbell
  - bicycle
  - bike
  - computer
  - screen
  - tv
  - helmet
  - display
  - pink
